# Ark Backup Cleaner Script #
---
- name: Ark Survival Evolved Backup Cleaner Script
  hosts: localhost
  become: true
  become_user: root
  gather_facts: yes
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  tasks:

  - name: get all but latest 5 files in folder
    shell:
      cmd: "ls -1tr /path/to/backup/drive/ark-backups/ | head --lines=-5"
    register: ls_cmd
    changed_when: ls_cmd.stdout_lines | length > 0

  - name: delete any older files
    when: ls_cmd.stdout_lines|length > 0
    file:
      path: /media/external/Server/One/ark-backups/{{ item }}
      state: absent
    loop: "{{ ls_cmd.stdout_lines }}"
    loop_control:
      label: "/path/to/backup/drive/ark-backups/{{ item }}"
