##############################################
#       Ark Survival Evolved - Updater       #
##############################################
---
- name: Ark Survival Evolved Launch Script
  hosts: localhost
  become: true
  become_user: arkserver
  gather_facts: yes
  tasks:

  - name: Stopping All Current Servers
    shell: |
      screen -S theisland -X quit
    delay: 5
